name = "BUR modpack"
author = "flexindahard"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00d3b4ea2519fe5e902075550c908e657f346946758feaa66269aa92e9d50c7c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
