name = "BUR modpack"
author = "flexindahard"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "174b0777c36752d9fc468494ce0c172e8cb9f97788e7f3ed42a532a273d25d53"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
