name = "BUR modpack"
author = "flexindahard"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9d10ee5f0a6a32a595a5af1d476e0cfc1a366494e7c74d54e0a1d90efe37876"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
